# 백기선님의 JAVA live-study

live-study(https://github.com/whiteship/live-study)

`9주차 목표`

자바의 예외 처리에 대해 학습하세요.


## 목차
<!-- TOC -->

- [목차](#목차)
- [Exception과 Error의 차이](#Exception(예외)와-Error(오류)의-차이) 
- [자바가 제공하는 예외 계층 구조](#자바가-제공하는-예외-계층-구조)
- [RuntimeException과 RE가 아닌 것의 차이](#RuntimeException과-RE가-아닌-것의-차이)
- [자바의 예외 처리 방법](#자바의-예외-처리-방법) <!-- try, catch, throw, throws, finally -->
- [커스텀한 예외 만드는 법](#커스텀한-예외-만드는-법)

## Exception(예외)와 Error(오류)의 차이
> 먼저 **오류(Error)란**, 작동하는 시스템에 예기치 못한 원인으로 프로그램이 오작동하거나 종료되는 그 원인을 말한다. 오류는 `StackOverFlowError`, `OutOfMemoryError` 등 JVM이나 HW같은 시스템상의 문제를 통칭한다.

Error가 발생 시, 프로그램은 종료되므로 이를 처리하는 것의 개발자의 영역 바깥의 문제이다.

<br>

하지만, **예외(Exception)** 는 개발자가 구현한 로직에서 발생한다. 다시 말하자면, 예외는 개발자가 미리 예측하고 처리할 수 있다.


## 자바가 제공하는 예외 계층 구조

<p align="center">
  <img src="../../assets/live-study_week9_01.png?raw=true">
</p>

이미지 출처:
[homebrew computer club](https://coco-log.tistory.com/31)

> 예외 클래스는 다음과 같이 RuntimeException(Unchecked Exception)과 나머지(Checked Exception)으로 나뉘게 된다. 

<br>

### RuntimeException과 RE가 아닌 것의 차이
먼저 `Checked Exception` 이란, 컴파일 시에 발생되는 예외를 말한다. 컴파일 타임에 발생하며(=컴파일러가 이를 체크해주며), 예외 처리가 반드시 요구된다. 하지만 `Runtime Exception`은 런타임 시 발생하며 컴파일러가 예외를 체크하지 않으므로, 이를 처리하는 것은 전적으로 프로그래머에게 달려 있다. 

* Checked Exception 의 대표 예시로 `IOException` 이 있다.
* Unchecked Exception(Runtime Exception)의 예시들
    * NullPointerException
    * ArrayIndexOutOfBoundsException
    * ArithmeticException(ex.DivideByZeroException)
    * ClassNotFoundException(클래스명을 실수로 잘못 적는 경우)

`Runtime Exception`의 종류를 살펴보면, 대부분 프로그램의 코드 문제로 발생되는 예외들이며 개발자가 충분히 해당 예외들을 고려하여 프로그램을 설계할 수 있는 문제들이다. 만일 컴파일러가 모든 Runtime Exception을 메서드에 명시하도록 강제한다면, 프로그램의 명확성을 떨어뜨릴 수 있다.

결론적으로 client가 exception을 회복할 수 있다고 생각되면 `checked exception`으로 만들고, 그렇지 않은 경우 `unchecked exception`으로 만드는 것을 권장한다.

<br>

## 자바의 예외 처리 방법

### try - catch문
**try - catch문**이란 `try 블럭`에서 예외 발생 가능성이 있는 실행문을 담고, 예외 발생시 `catch 블럭`을 통해 예외를 처리하는 구문이다. 구조는 다음과 같다.

~~~java
try {
    // 예외 발생할 가능성이 있는 실행문
} catch(Exception1 e1){
    // Exception1이 발생했을 경우, 이를 처리하기 위한 실행문
} catch(Exception2 e2){
    // Exception2이 발생했을 경우, 이를 처리하기 위한 실행문
}
~~~

`catch 블럭`은 여러 개를 작성할 수 있으며, 이 중에 발생한 예외의 종류와 딱 맞는 단 하나의 `catch 블럭`만 수행된다. 

~~~java 
// ArithmeticException 예시
public class ExceptionEx {
    public static void main(String[] args){
        int number = 10;
        int divisor = 0;
        int res;

        try{
            res = (number / divisor);
        } catch (ArithmeticException e){
            System.out.println("0으로 나눌 수 없습니다.");
        }
    }
}

// 0으로 나눌 수 없습니다.
~~~

위 코드는 정수 `number`을 0으로 나누려고 시도하여 `ArithmeticException`이 발생하였으나, catch문을 거쳐 message가 출력되는 모습이다. 이처럼 catch문의 괄호 내에는 처리하고자 하는 예외와 같은 타입의 참조변수 하나를 선언해야 한다. 모든 예외 클래스는 `Exception` 클래스의 자손이므로, catch 블럭의 괄호()에 `Exception` 타입의 참조변수를 선언하면 모든 오류들이 이 catch 블럭에 의해서 처리된다.

<br>

그렇다면, 만약 ExceptionEx 클래스에서 catch(Exception e2) 문을 추가하면 어떻게 될까? 
* `ArithmeticException` catch 블럭보다 앞에 위치시킬 경우, 다음과 같은 오류 메세지가 발생한다.
>java: exception java.lang.ArithmeticException has already been caught

그러나 `ArithmeticException` catch 블럭보다 뒤에 위치시킬 경우에는 해당 블록의 실행문이 실행되는 것을 확인할 수 있었다.
>출력 결과 : 0으로 나눌 수 없습니다.

즉, catch문은 순차적으로 실행되며 **부모 클래스가 자식 클래스보다 먼저 catch에 사용되면 컴파일 에러가 발생한다.**

<br>
* Java 7부터, catch문의 참조변수를 `|` 기호를 이용해 여러 참조변수를 함께 작성할 수 있게 되었다. 단, 상속 관계에 있는 참조변수들은 함께 작성할 수 없다.

### finally
> `finally` 블럭은 예외의 발생 여부에 관계 없이 무조건 실행되어야 하는 문장을 적어 사용한다. 구조는 try-catch-finally 순으로 구성되어 있다. 실행되는 순서도 동일하다.

~~~java
class FinallyEx {
    public static void main(String[] args){
        FinallyEx.printMsg();
    }

    static void printMsg(){
        try {
            System.out.println("printMsg() 메소드가 실행 되었습니다.");
            return; // 메서드 종료.
        } catch (Exception e){
            e.printStackTrace();
        } finally {
            System.out.println("finally 블록은 반드시 실행됩니다.");
        }
    }
}

// 결과 : printMsg() 메소드가 실행 되었습니다.
//        finally 블록은 반드시 실행됩니다. 
~~~

try 블럭에서 return문이 실행되어도 finally 블럭을 실행한 후에 메서드를 종료하게 된다.

`finally` 블럭에는 주로 cleanup code를 적어 Resource leak을 방지하는 것이 좋다. 


<!-- 
### Java Exception 내용 출력하기
~~~java
e.getMessage() : 에외 클래스의 인스턴스에 저장된 메세지를 출력

e.toString() : 에러의 Exception 내용과 원인을 출력

e.printStackTrace() : 에러의 발생 근원지를 찾아 단계별로 에러를 출력
~~~
-->

<br>

### throw
개발자는 `throw` 키워드를 이용해 고의로 에러를 발생시킬 수 있다. 발생시킨 에러는 상위 블럭이나 catch문으로 예외를 던진다. 기본 문법은 다음과 같다.
> throw new 발생시킬 예외  or  throw 예외 클래스의 인스턴스 객체

예제를 살펴보자.

~~~java
class ExceptionForThrow {
    public static void main(String[] args){
        try{
            Exception e = new Exception();
            throw e // 임의로 예외 발생.
            throw new Exception(); // 임의로 예외 발생.
            
        } catch (Exception e){
            System.out.println("예외를 처리했습니다.")
        }
    }
}
// 결과 : 예외를 처리했습니다.
~~~

### throws

try - catch 문 말고도 `throws`를 통해 예외를 메서드에 선언하는 방식으로도 예외를 처리할 수 있다.
메서드를 정의할 때, `throws`를 사용해서 메서드 내에서 발생할 수 있는 예외를 나열해주면 된다.

~~~java
void 메소드명() throws Exception1, Exception2 ... {
    //executable
}
~~~

`throws`를 통해 던져진 예외들은 해당 메소드를 호출하는 곳에서 예외 처리를 해 주어야 한다. 
다시 말해서, `throws`는 예외 처리에 대한 책임을 전가하는 역할을 한다.

~~~java
class Test {
    public static void calculate() throws ArithmeticException {
        int a = 0;
        a = 10 / a;
    }

    public static void main(String[] args){
        try { 
            Test.calculate();
        } catch(Exception e){
            System.out.println("실행하는 메소드에서 예외를 처리합니다.");
        }
    }
}
~~~

개발자들은 `throws`를 통해 어떤 메소드를 호출하여 사용 시에 발생할 수 있는 예외들을 
사전에 알릴 수 있다는 점에서 의의가 있다.


## 커스텀한 예외 만드는 법
> 기존에 정의된 Exception 클래스 외에도 자신만의 예외 클래스를 만들 수 있다.

* Checked Exception을 만드는 경우에는 Exception 클래스를 상속받아 구현할 수 있다.
* Unchecked Exception을 만드는 경우에는 RuntimeException 클래스를 상속받아 구현할 수 있다.
* 생성자는 기본 생성자와, 예외 메세지를 전달하기 위해 String 타입의 파라미터를 갖는 생성자 총 두 개를 생성하는 것이 좋다.
* 예외 메세지는 catch 블럭에서 사용된다.

~~~java
class MyException extends Exception {
    public MyException(String s)
    {
        super(s);
    }
}
 
public class Main {
    public static void main(String args[])
    {
        try {
            throw new MyException("Msg");
        }
        catch (MyException ex) {
            System.out.println("Caught");
 
            // Print the message from MyException object
            System.out.println(ex.getMessage());
        }
    }
}

/* 결과
Caught
Msg
*/
~~~


## 출처
* https://www.geeksforgeeks.org/checked-vs-unchecked-exceptions-in-java
* https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html
* https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/try...catch#%EC%84%A4%EB%AA%85
* https://www.geeksforgeeks.org/throw-throws-java
* https://www.geeksforgeeks.org/user-defined-custom-exception-in-java
* Java의 정석 (p416 ~ p424)
